# Generated by Django 3.0.5 on 2020-05-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
    ]
